workflow:
  rules:

    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

    - if: '$CI_PIPELINE_SOURCE =~ /^(pipeline|parent_pipeline|trigger|api|web|schedule)$/'

    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

    - if: '$CI_COMMIT_BRANCH =~ /^release\//'
    - if: '$CI_COMMIT_TAG'
    
    - when: never

include:
  - '.gitlab/ci/common.yml'
  - '.gitlab/ci/sync_test_branch.yml'
  - '.gitlab/ci/generate_build_test_jobs.yml'
  - '.gitlab/ci/docs.yml'
  - '.gitlab/ci/check_typos.yml'
