/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#include <ezbee/zcl/cluster/price_desc.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Maximum length of the tier label.
 */
#define EZB_ZCL_PRICE_TIER_LABEL_MAX_LENGTH 13

/**
 * @brief Maximum length of the rate label.
 */
#define EZB_ZCL_PRICE_RATE_LABEL_MAX_LENGTH 13

/**
 * @brief Command options for the ZCL Price Get Current Price command.
 */
typedef enum ezb_zcl_price_get_current_price_cmd_opts_s {
    EZB_ZCL_PRICE_GET_CURRENT_PRICE_CMD_OPT_REQUESTOR_RX_ON_WHEN_IDLE = (1U << 0),
} ezb_zcl_price_get_current_price_cmd_opts_t;

/**
 * @brief Payload for the ZCL Price Get Scheduled Prices command.
 */
typedef struct ezb_zcl_price_get_scheduled_prices_payload_s {
    uint32_t start_time;    /*!< Start Time. */
    uint8_t  num_of_events; /*!< Number of Events. */
} ezb_zcl_price_get_scheduled_prices_payload_t;

/**
 * @brief Payload for the ZCL Price Price Ack command.
 */
typedef struct ezb_zcl_price_price_ack_payload_s {
    uint32_t provider_id;     /*!< Provider ID. */
    uint32_t issuer_event_id; /*!< Issuer Event ID. */
    uint32_t price_ack_time;  /*!< Price Acknowledgment Time. */
    uint8_t  control;         /*!< Command Options. */
} ezb_zcl_price_price_ack_payload_t;

/**
 * @brief Payload for the ZCL Price Publish Price command.
 */
EZB_PACKED_BEGIN
struct ezb_zcl_price_publish_price_payload_s {
    /* Mandatory fields. */
    uint32_t provider_id;                                     /*!< Unique identifier for the commodity provider. */
    uint8_t  rate_label[EZB_ZCL_PRICE_RATE_LABEL_MAX_LENGTH]; /*!< Commodity provider-specific information regarding the current
                                                                 billing rate. */
    uint32_t issuer_event_id; /*!< Unique identifier generated by the commodity provider allows devices to determine which
                              pricing information is newer. */
    uint32_t current_time;    /*!< UTC Time field containing the current time as determined by the device. */
    uint8_t  unit_of_measure; /*!< Field identifying the commodity as well as this base units of measure. */
    uint16_t currency; /*!< Field identifying information concerning the local unit of currency used in the price field. */
    uint8_t  price_trailing_digit : 4;  /*!< Determines where the decimal point is located in the price field. */
    uint8_t  price_tier : 4;            /*!< Indicates the current price tier as chosen by the commodity provider. */
    uint8_t  number_of_price_tiers : 4; /*!< Represents the maximum number of price tiers available. */
    uint8_t  register_tier : 4;         /*!< Indicates the register tier used with the current Price Tier. */
    uint32_t start_time; /*!< Denotes the time at which the signal becomes valid. Value 0x00000000 is a special time denoting
                         "now". */
    uint16_t duration_in_minutes; /*!< Denotes amount of time in minutes after Start Time during which the price signal is
                                  valid. */
    uint32_t price; /*!< Contains the price of the commodity measured in base unit of Currency per Unit of Measure with the
                    decimal point located as indicated by the Price Trailing Digit field when the commodity is delivered to
                    premises. */
    /* Optional fields. */
    uint8_t price_ratio;       /*!< Gives the ratio of the price denoted in the Price field to the "normal" price, chosen by the
                               commodity provider. */
    uint32_t generation_price; /*!< Contains the price of the commodity measured in base unit of Currency per Unit of Measure
                               with the decimal point located as indicated by the Price Trailing Digit field when the commodity
                               is received from premises. */
    uint8_t generation_price_ratio;    /*!< Gives the ratio of the price denoted in the Generation Price field to the "normal"
                                       price, chosen by the commodity provider. */
    uint32_t alternate_cost_delivered; /*!< Provides mechanism to describe an alternative measure of the cost of the energy
                                       consumed. */
    uint8_t alternate_cost_unit;       /*!< Identifies the unit for Alternate Cost Delivered field. */
    uint8_t alternate_cost_trailing_digit; /*!< Determines where the decimal point is located in the alternate cost field. */
    uint8_t number_of_block_thresholds;    /*!< Indicates the number of block thresholds available. */
    uint8_t price_control; /*!< Identifies additional control options (PriceAcknowledgement policy and total number of tier
                           flag). */
    uint8_t number_of_generation_tiers; /*!< Specifies the total number of generation tiers applicable in the current tariff. */
    uint8_t generation_tier;            /*!< Specifies the current generation tier. */
    uint8_t extended_number_of_price_tiers; /*!< Indicates a maximum number of tier available. */
    uint8_t extended_price_tier;            /*!< Indicates the current price tier. */
    uint8_t extended_register_tier;         /*!< Indicates the register tier used with the current Price Tier. */
} EZB_PACKED_END;
/**
 * @brief Payload for the ZCL Price Publish Price command.
 */
typedef struct ezb_zcl_price_publish_price_payload_s ezb_zcl_price_publish_price_payload_t;

/**
 * @brief Tier information for Price Publish Tier Labels command.
 */
typedef struct ezb_zcl_price_tier_label_entry_s {
    uint8_t tier_id;                                         /*!< The tier number that the associated TierLabel applies to. */
    uint8_t tier_label[EZB_ZCL_PRICE_TIER_LABEL_MAX_LENGTH]; /*!< Octet String field capable of storing a 12 character string
                            (the first character indicates the string length, represented in hexadecimal format) encoded in the
                            UTF-8 format. */
} ezb_zcl_price_tier_label_entry_t;

/**
 * @brief Payload for the ZCL Price Publish Tier Labels command.
 */
typedef struct ezb_zcl_price_publish_tier_labels_payload_s {
    uint32_t provider_id;      /*!< An unsigned 32-bit field containing a unique identifier for the commodity provider. */
    uint32_t issuer_event_id;  /*!< Unique identifier generated by the commodity provider. */
    uint32_t issuer_tariff_id; /*!< Unique identifier generated by the commodity supplier. */
    uint8_t  command_index; /*!< This is used to count the payload fragments in the case where the entire payload does not fit
                            into one message. */
    uint8_t total_number_of_commands;              /*!< In the case where the entire payload does not fit into one message,
                                                   this field indicates the total number of sub-commands in the message. */
    uint8_t number_of_labels;                      /*!< The number of TierID/Tier Label sets contained within the command. */
    ezb_zcl_price_tier_label_entry_t *tier_labels; /*!< Tier labels published in the command */
} ezb_zcl_price_publish_tier_labels_payload_t;

/**
 * @brief Structure for the ZCL Price Get Current Price command.
 */
typedef struct ezb_zcl_price_get_current_price_cmd_s {
    ezb_zcl_cluster_cmd_ctrl_t cmd_ctrl; /*!< Control information for the ZCL command. */
    struct {
        uint8_t cmd_opts; /*!< Command options. */
    } payload;            /*!< Payload of Get Current Price command. */
} ezb_zcl_price_get_current_price_cmd_t;

/**
 * @brief Structure for the ZCL Price Get Scheduled Prices command.
 */
typedef struct ezb_zcl_price_get_scheduled_prices_cmd_s {
    ezb_zcl_cluster_cmd_ctrl_t                   cmd_ctrl; /*!< Control information for the ZCL command. */
    ezb_zcl_price_get_scheduled_prices_payload_t payload;  /*!< Payload of Get Scheduled Prices command. */
} ezb_zcl_price_get_scheduled_prices_cmd_t;

/**
 *  @brief Structure for the ZCL Price Get Tier Labels command.
 */
typedef struct ezb_zcl_price_get_tier_labels_cmd_s {
    ezb_zcl_cluster_cmd_ctrl_t cmd_ctrl; /*!< Control information for the ZCL command. */
    struct {
        uint32_t issuer_tariff_id; /*!< Issuer Tariff ID. */
    } payload;                     /*!< Payload of Get Tier Labels command. */
} ezb_zcl_price_get_tier_labels_cmd_t;

/**
 * @brief Structure for the ZCL Price Publish Price command.
 */
typedef struct ezb_zcl_price_publish_price_cmd_s {
    ezb_zcl_cluster_cmd_ctrl_t            cmd_ctrl; /*!< Control information for the ZCL command. */
    ezb_zcl_price_publish_price_payload_t payload;  /*!< Payload of Publish Price Command. */
} ezb_zcl_price_publish_price_cmd_t;

/**
 * @brief Structure for the ZCL Price Publish Tier Labels command.
 */
typedef struct ezb_zcl_price_publish_tier_labels_cmd_s {
    ezb_zcl_cluster_cmd_ctrl_t                  cmd_ctrl; /*!< Control information for the ZCL command. */
    ezb_zcl_price_publish_tier_labels_payload_t payload;  /*!< Payload of Publish Tier Labels Command. */
} ezb_zcl_price_publish_tier_labels_cmd_t;

/**
 * @brief Message for the ZCL Price Get Current Price command message.
 */
typedef struct ezb_zcl_price_get_current_price_message_s {
    ezb_zcl_message_info_t info; /*!< Basic information about the ZCL message. */
    struct {
        const ezb_zcl_cmd_hdr_t *header; /*!< ZCL command header information.
                                              See @ref ezb_zcl_cmd_hdr_s. */
        uint8_t cmd_opts; /*!< Command options. */
    } in;                 /*!< Input: parsed fields from the request. */
    struct {
        ezb_zcl_status_t result; /*!< Status of processing in application. */
    } out;                       /*!< Output: result to send back. */
} ezb_zcl_price_get_current_price_message_t;

/**
 * @brief Message for the ZCL Price Get Scheduled Prices command message.
 */
typedef struct ezb_zcl_price_get_scheduled_prices_message_s {
    ezb_zcl_message_info_t info; /*!< Basic information about the ZCL message. */
    struct {
        const ezb_zcl_cmd_hdr_t *header; /*!< ZCL command header information.
                                              See @ref ezb_zcl_cmd_hdr_s. */
        ezb_zcl_price_get_scheduled_prices_payload_t payload; /*!< Payload of Get Scheduled Prices command. */
    } in;                                                     /*!< Input: parsed fields from the request. */
    struct {
        ezb_zcl_status_t result; /*!< Status of processing in application. */
    } out;                       /*!< Output: result to send back. */
} ezb_zcl_price_get_scheduled_prices_message_t;

/**
 * @brief Message for the ZCL Price Price Ack command message.
 */
typedef struct ezb_zcl_price_price_ack_message_s {
    ezb_zcl_message_info_t info; /*!< Basic information about the ZCL message. */
    struct {
        const ezb_zcl_cmd_hdr_t *header; /*!< ZCL command header information.
                                              See @ref ezb_zcl_cmd_hdr_s. */
        ezb_zcl_price_price_ack_payload_t payload; /*!< Payload of Price Ack command. */
    } in;                                          /*!< Input: parsed fields from the request. */
    struct {
        ezb_zcl_status_t result; /*!< Status of processing in application. */
    } out;                       /*!< Output: result to send back. */
} ezb_zcl_price_price_ack_message_t;

/**
 * @brief Message for the ZCL Price Get Tier Labels command message.
 */
typedef struct ezb_zcl_price_get_tier_labels_message_s {
    ezb_zcl_message_info_t info; /*!< Basic information about the ZCL message. */
    struct {
        const ezb_zcl_cmd_hdr_t *header; /*!< ZCL command header information.
                                              See @ref ezb_zcl_cmd_hdr_s. */
        uint32_t issuer_tariff_id; /*!< Issuer Tariff ID. */
    } in;                          /*!< Input: parsed fields from the request. */
    struct {
        ezb_zcl_status_t                             result;  /*!< Status of processing in application. */
        ezb_zcl_price_publish_tier_labels_payload_t *payload; /*!< Payload of Publish Tier Labels command. */
        ezb_zcl_cmd_cnf_ctx_t cnf_ctx; /*!< Command confirmation context, which will be triggered when response is confirmed. */
    } out;                             /*!< Output: result to send back. */
} ezb_zcl_price_get_tier_labels_message_t;

/**
 * @brief Message for the ZCL Price Publish Price command message.
 */
typedef struct ezb_zcl_price_publish_price_message_s {
    ezb_zcl_message_info_t info; /*!< Basic information about the ZCL message. */
    struct {
        const ezb_zcl_cmd_hdr_t *header; /*!< ZCL command header information.
                                              See @ref ezb_zcl_cmd_hdr_s. */
        ezb_zcl_price_publish_price_payload_t payload; /*!< Payload of Publish Price command. */
    } in;                                              /*!< Input: parsed fields from the request. */
    struct {
        ezb_zcl_status_t result; /*!< Status of processing in application. */
    } out;                       /*!< Output: result to send back. */
} ezb_zcl_price_publish_price_message_t;

/**
 * @brief Message for the ZCL Price Publish Tier Labels command message.
 */
typedef struct ezb_zcl_price_publish_tier_labels_message_s {
    ezb_zcl_message_info_t info; /*!< Basic information about the ZCL message. */
    struct {
        const ezb_zcl_cmd_hdr_t *header; /*!< ZCL command header information.
                                              See @ref ezb_zcl_cmd_hdr_s. */
        ezb_zcl_price_publish_tier_labels_payload_t payload; /*!< Payload of Publish Tier Labels command. */
    } in;                                                    /*!< Input: parsed fields from the request. */
    struct {
        ezb_zcl_status_t result; /*!< Status of processing in application. */
    } out;                       /*!< Output: result to send back. */
} ezb_zcl_price_publish_tier_labels_message_t;

/**
 * @brief Send ZCL Price Get Current Price command request.
 *
 * @param cmd_req Pointer to the Get Current Price command request structure.
 * @return Error code.
 */
ezb_err_t ezb_zcl_price_get_current_price_cmd_req(const ezb_zcl_price_get_current_price_cmd_t *cmd_req);

/**
 * @brief Send ZCL Price Get Scheduled Prices command request.
 *
 * @param cmd_req Pointer to the Get Scheduled Prices command request structure.
 * @return Error code.
 */
ezb_err_t ezb_zcl_price_get_scheduled_prices_cmd_req(const ezb_zcl_price_get_scheduled_prices_cmd_t *cmd_req);

/**
 * @brief Send ZCL Price Get Tier Labels command request.
 *
 * @param cmd_req Pointer to the Get Tier Labels command request structure
 * @return Error code.
 */
ezb_err_t ezb_zcl_price_get_tier_labels_cmd_req(const ezb_zcl_price_get_tier_labels_cmd_t *cmd_req);

/**
 * @brief Send ZCL Price Publish Price command request.
 *
 * @param cmd_req Pointer to the Publish Price command request structure.
 * @note In the case of an update to the pricing information from the commodity provider, the Publish Price
 *       command should be unicast to all individually registered devices implementing the Price Cluster on
 *       the ZigBee Smart Energy network. In spec 10.2.2.4.1.
 * @return Error code.
 */
ezb_err_t ezb_zcl_price_publish_price_cmd_req(const ezb_zcl_price_publish_price_cmd_t *cmd_req);

/**
 * @brief Send ZCL Price Publish Tier Labels command request.
 *
 * @param cmd_req Pointer to the Publish Tier Labels command request structure
 * @return Error code.
 */
ezb_err_t ezb_zcl_price_publish_tier_labels_cmd_req(const ezb_zcl_price_publish_tier_labels_cmd_t *cmd_req);

#ifdef __cplusplus
} /* extern "C" */
#endif
