# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

.config_radio_native_targets: &config_radio_native_targets
  enable:
    - if: SOC_IEEE802154_SUPPORTED == 1
    - if: IDF_TARGET in ["esp32c6", "esp32h2"]
    - if: IDF_TARGET == "esp32c5" and (IDF_VERSION >= "v5.5" or IDF_VERSION == "master")
      temporary: true
      reason: esp32c5 is only supported in IDF v5.5+

.config_rcp_host_targets: &config_rcp_host_targets
  enable:
    - if: IDF_TARGET in ["esp32", "esp32s2", "esp32c3", "esp32s3", "esp32c6"]
      temporary: true
      reason: the other targets are not tested yet
    - if: IDF_TARGET == "esp32c5" and (IDF_VERSION >= "v5.5" or IDF_VERSION == "master")
      temporary: true
      reason: esp32c5 is only supported in IDF v5.5+

.example_no_build: &example_no_build
  disable:
    - if: INCLUDE_DEFAULT == 1

examples/zigbee_gateway:
  <<: *config_rcp_host_targets

examples/all_device_types_app:
  <<: *config_radio_native_targets

examples/ota_upgrade/ota_client:
  <<: *config_radio_native_targets

examples/ota_upgrade/ota_server:
  <<: *config_radio_native_targets

examples/home_automation_devices/thermostat:
  <<: *config_radio_native_targets

examples/home_automation_devices/temperature_sensor:
  <<: *config_radio_native_targets

examples/home_automation_devices/color_dimmable_light:
  <<: *config_radio_native_targets

examples/home_automation_devices/color_dimmer_switch:
  <<: *config_radio_native_targets

examples/home_automation_devices/on_off_light:
  <<: *config_radio_native_targets

examples/home_automation_devices/on_off_switch:
  <<: *config_radio_native_targets

examples/sleepy_devices/deep_sleep_end_device:
  <<: *config_radio_native_targets

examples/sleepy_devices/light_sleep_end_device:
  <<: *config_radio_native_targets

examples/customized_devices/data_consumer:
  <<: *config_radio_native_targets

examples/customized_devices/data_producer:
  <<: *config_radio_native_targets

examples/touchlink/touchlink_initiator:
  <<: *config_radio_native_targets

examples/touchlink/touchlink_target:
  <<: *config_radio_native_targets
